### ISSUE TITLE
BigIp name char limit exceeded - GCP internal DNS names too long for Canadian and European regions

### ISSUE THREAD

**Issue by AnthonyF5** [JeffGiroux/f5_terraform#58]
Repo: https://github.com/JeffGiroux/f5_terraform/tree/main/GCP/HA_via_api

Issue where the longer GCP regions e.g. Canada northamerica-northeast1 when pulled in via the GCP metadata server to create the BigIP name break the 64 char limit.
Example is mydemo123-bigip1-28a4.northamerica-northeast1-a.c.th-mysandbox-lab-56c8bd.internal 

**Use a variable to manage the name:**
1) Add variable domain_name to variables with a default of example.com
2) Add variable domain_name to terraform.tfvars 
3) Add domain_name = var.domain_name to bigip.tf for locals f5_onboard1 and f5_onboard2.
4) Update f5_onboard.tmpl 3 lines below to leverage the variable:

Line 153: http://169.254.169.254/computeMetadata/v1/instance/name
Line 214: ui.advisory.text: '{{{ HOST_NAME }}}.${domain_name}'
Line 218: hostname: '{{{ HOST_NAME }}}.${domain_name}'

**Comment by JeffGiroux** [comment]
Will look into this.

In the meantime, quick workaround is to update the bigip.tf file to supply a shortened name. After scrubbing code, I realize I set a fixed name with dynamic variables. Need to adjust for user input as mentioned.

```
module "bigip" {
  source                            = "F5Networks/bigip-module/gcp"
  version                           = "1.1.9"
  prefix                            = var.projectPrefix
  vm_name                           = format("%s-bigip1-%s", var.projectPrefix, random_id.buildSuffix.hex)
```

Maybe with the region dns suffix, this might not be short enough. The dns name was required initially for reachability in setting up HA peer. But...IPs work too...so DNS name of example.com though unreachable as FQDN from an HA peering attempt is OK because the onboard will use IP for cluster.

**Comment by JeffGiroux** [comment]
'dns_suffix' is meant for this purpose. It's used in Azure, but I don't have it implemented in Google yet...

**Comment by AnthonyF5** [comment]
Thanks for the info, that simplifies things using the dns_suffix on GCP. I tested the below change (no new variable) and it worked as intended.

**Update f5_onboard.tmpl 3 lines below to leverage the variable:**
Line 153: http://169.254.169.254/computeMetadata/v1/instance/name
Line 214: ui.advisory.text: '{{{ HOST_NAME }}}.${dns_suffix}'
Line 218: hostname: '{{{ HOST_NAME }}}.${dns_suffix}'
